### ISSUE TITLE
获取 Azure AD 令牌 - 在azure china中，请求参数和请求body不对

### ISSUE THREAD

**Issue by bet2019** [MicrosoftDocs/mc-docs.zh-cn#15]
在Azure China中，执行“获取 Azure AD 令牌步骤”
第3步：将会发送以下 POST 操作。
1. https://login.partner.microsoftonline.cn/:tenantId/oauth2/token，GitHub的postman没tenantId这个参数
2. https://login.partner.microsoftonline.cn/:tenantId/oauth2/token，GitHub的postman的请求body的resource应该是https://management.chinacloudapi.cn

对不知道Azure 资源管理 (ARM)的来说，会有请求失败

**Comment by Derek1101** [comment]
An issue https://github.com/MicrosoftDocs/azure-docs/issues/64201  is created to track this issue, will keep following up.

**Comment by Derek1101** [comment]
Fixed already.
