### ISSUE TITLE
includes/cognitive-services-speech-service-rest-auth.md curl returns 404

### ISSUE THREAD

**Issue by fc13240** [MicrosoftDocs/mc-docs.zh-cn#5]
curl -v -X POST
 "https://chinaeast2.api.cognitive.azure.cn/sts/v1.0/issueToken" \
 -H "Content-type: application/x-www-form-urlencoded" \
 -H "Content-Length: 0" \
 -H "Ocp-Apim-Subscription-Key: YOUR_SUBSCRIPTION_KEY"

is returns 404

<img width="871" alt="屏幕快照 2019-11-28 16 57 43" src="https://user-images.githubusercontent.com/5786628/69791976-9823bb80-1200-11ea-9a7e-27833f3fce7c.png">

**Comment by Derek1101** [comment]
Fixed.
